services:
  postgres:
    image: postgres:16
    container_name: apicuentas-postgres
    environment:
      POSTGRES_DB: apicuentas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apicuentas-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=apicuentas;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: