// <auto-generated />
using System;
using ApiCuentas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiCuentas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725051605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiCuentas.Domain.Entities.Cuenta", b =>
                {
                    b.Property<string>("IdCuenta")
                        .HasColumnType("text")
                        .HasColumnName("id_cuenta");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_cuenta");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_cuenta");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titular");

                    b.HasKey("IdCuenta")
                        .HasName("pk_cuentas");

                    b.ToTable("cuentas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
