apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: accounts
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SEQ_FIRSTRUN_ADMINUSERNAME
              value: "admin"
            - name: SEQ_FIRSTRUN_ADMINPASSWORD
              value: "123456"
